apiVersion: v1
kind: PersistentVolume
metadata:
  name: scripto-storage-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # Pod이 삭제되어도 물리 데이터는 유지하는 정책
  nfs:
    server: 192.168.0.86  # 현재 로키 리눅스 IP
    path: /nfs/scripto/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scripto-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
