apiVersion: v1
kind: Service
metadata:
  name: velo-main-service
  namespace: default
  labels:
    app: velo-main-service
spec:
  # NodePort 방식으로 설정하여 로키 리눅스 자체 하드웨어 포트를 개방합니다.
  type: NodePort
  selector:
    app: velo-main-api # 중요: deployment.yaml에 적은 레플리카 3개의 라벨과 정확히 일치해야 3대로 신호를 보냅니다.
  ports:
  - port: 8080          # 쿠버네티스 서비스 내부망에서 사용하는 포트
    targetPort: 8080    # 스프링 부트 컨테이너들의 진짜 포트
    nodePort: 30080     # [Nginx 연동 포트] 외부 Nginx가 proxy_pass로 찔러줄 리눅스 포트
