package cloud.velo.main.util.template.initializer.framework;

import cloud.velo.main.controller.dto.ProjectCreateRequestDto;
import cloud.velo.main.util.template.BaseTemplateInitializer;
import org.springframework.stereotype.Component;

import java.nio.file.Path;
import java.util.List;

@Component
public class NextJsTemplateInitializer extends BaseTemplateInitializer {

    @Override
    public String getSupportedFramework() { return "nextjs"; }

    @Override
    public void initTemplate(Path rootPath, ProjectCreateRequestDto dto) {
        String projectName = dto.getArtifact().toLowerCase();

        createDirectories(rootPath, List.of(
                "src/app",
                "src/components/ui",
                "src/hooks",
                "src/lib",
                "src/types",
                "src/api",
                "public"
        ));

        writeFile(rootPath.resolve("src/app/layout.tsx"), layoutTsx(projectName));
        writeFile(rootPath.resolve("src/app/page.tsx"), pageTsx());
        writeFile(rootPath.resolve("src/app/globals.css"), globalsCss());
        writeFile(rootPath.resolve("src/lib/utils.ts"), utilsTs());
        writeFile(rootPath.resolve("src/api/index.ts"), apiIndex());
        writeFile(rootPath.resolve("package.json"), packageJson(projectName));
        writeFile(rootPath.resolve("next.config.ts"), nextConfig());
        writeFile(rootPath.resolve("tsconfig.json"), tsconfig());
        writeFile(rootPath.resolve(".env.example"), envExample());
        writeFile(rootPath.resolve(".gitignore"), nextGitignore());
        writeFile(rootPath.resolve("README.md"), readme(projectName, dto.getLicense()));
    }

    private String layoutTsx(String projectName) {
        return """
                import type { Metadata } from 'next'
                import { Inter } from 'next/font/google'
                import './globals.css'
                
                const inter = Inter({ subsets: ['latin'] })
                
                export const metadata: Metadata = {
                  title: '%s',
                  description: 'Generated by project generator',
                }
                
                export default function RootLayout({ children }: { children: React.ReactNode }) {
                  return (
                    <html lang="ko">
                      <body className={inter.className}>{children}</body>
                    </html>
                  )
                }
                """.formatted(capitalize(projectName));
    }

    private String pageTsx() {
        return """
                export default function Home() {
                  return (
                    <main>
                      <h1>Hello World</h1>
                    </main>
                  )
                }
                """;
    }

    private String globalsCss() {
        return """
                * {
                  box-sizing: border-box;
                  padding: 0;
                  margin: 0;
                }
                
                html, body {
                  max-width: 100vw;
                  overflow-x: hidden;
                }
                """;
    }

    private String utilsTs() {
        return """
                import { type ClassValue, clsx } from 'clsx'
                import { twMerge } from 'tailwind-merge'
                
                export function cn(...inputs: ClassValue[]) {
                  return twMerge(clsx(inputs))
                }
                """;
    }

    private String apiIndex() {
        return """
                const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL
                
                export async function fetcher<T>(url: string, options?: RequestInit): Promise<T> {
                  const res = await fetch(`${BASE_URL}${url}`, {
                    headers: { 'Content-Type': 'application/json' },
                    ...options,
                  })
                  if (!res.ok) throw new Error('API Error')
                  return res.json()
                }
                """;
    }

    private String packageJson(String projectName) {
        return """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "lint": "next lint"
                  },
                  "dependencies": {
                    "next": "15.0.0",
                    "react": "^19.0.0",
                    "react-dom": "^19.0.0",
                    "clsx": "^2.1.0",
                    "tailwind-merge": "^2.5.0"
                  },
                  "devDependencies": {
                    "@types/node": "^22.0.0",
                    "@types/react": "^19.0.0",
                    "typescript": "^5.0.0",
                    "tailwindcss": "^3.4.0"
                  }
                }
                """.formatted(projectName);
    }

    private String nextConfig() {
        return """
                import type { NextConfig } from 'next'
                
                const nextConfig: NextConfig = {
                  async rewrites() {
                    return [
                      {
                        source: '/api/:path*',
                        destination: `${process.env.API_BASE_URL}/api/:path*`,
                      },
                    ]
                  },
                }
                
                export default nextConfig
                """;
    }

    private String tsconfig() {
        return """
                {
                  "compilerOptions": {
                    "target": "ES2017",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": true,
                    "skipLibCheck": true,
                    "strict": true,
                    "noEmit": true,
                    "esModuleInterop": true,
                    "module": "esnext",
                    "moduleResolution": "bundler",
                    "resolveJsonModule": true,
                    "isolatedModules": true,
                    "jsx": "preserve",
                    "incremental": true,
                    "paths": {
                      "@/*": ["./src/*"]
                    }
                  },
                  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
                  "exclude": ["node_modules"]
                }
                """;
    }

    private String envExample() {
        return """
                NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
                API_BASE_URL=http://localhost:8080
                """;
    }

    private String nextGitignore() {
        return """
                node_modules/
                .next/
                out/
                .env
                .env.local
                .DS_Store
                *.tsbuildinfo
                next-env.d.ts
                """;
    }

    private String readme(String projectName, String license) {
        return """
                # %s
                
                ## Getting Started
                
                ### Prerequisites
                - Node.js 20+
                
                ### Run
```bash
                npm install
                npm run dev
```
                
                ## License
                %s
                """.formatted(projectName, license);
    }
}